---
- name: Installer ClamAV
  hosts: all
  become: yes
  vars:
    ansible_remote_tmp: /tmp/.ansible
    
  environment:
    ANSIBLE_REMOTE_TMP: /tmp/.ansible
    ANSIBLE_HOST_KEY_CHECKING: "False"
    ANSIBLE_SSH_ARGS: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    
  roles:
    - .
