---
- name: Installer ClamAV
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  become_flags: '-H'
  
  # AJOUTEZ CES VARIABLES
  vars:
    ansible_remote_tmp: /tmp/.ansible
  
  environment:
    ANSIBLE_REMOTE_TEMP: /tmp/.ansible
    ANSIBLE_HOST_KEY_CHECKING: "False"
  
  roles:
    - .
