---
- name: Installer ClamAV
  hosts: all
  become: true
  vars:
    ansible_remote_tmp: /tmp/.ansible
    
  environment:
    ANSIBLE_REMOTE_TMP: /tmp/.ansible
    ANSIBLE_HOST_KEY_CHECKING: "False"
    
  roles:
    - .
